from __future__ import annotations

RSI_TREND_MIN = 52
RSI_TREND_MAX = 66
RSI_PULLBACK_MIN = 42
RSI_PULLBACK_MAX = 55
RSI_BREAKOUT_MIN = 55
RSI_BREAKOUT_MAX = 72
RSI_RECOVERY_CROSS = 45

W_RSI_ZONE = 25
W_MOMENTUM_TURN = 25
W_TREND_FILTER = 20
W_EXTENSION_RISK = 15
W_VOLUME = 10
W_DATA_QUALITY = 5

MAX_DISTANCE_EMA21_PCT = 8.0
BREAKOUT_MAX_DIST_FROM_20D_HIGH = 3.0
MIN_VOL_REL_BREAKOUT = 1.2

DEFAULT_PERIOD = "1y"
DEFAULT_MIN_SCORE = 60
DEFAULT_MAX_TICKERS = 50

SWING_WINDOW = 3
CLUSTER_PCT = 1.0
MAX_LEVELS_EACH_SIDE = 3

IBOVESPA_TICKERS = [
    "PETR4.SA", "VALE3.SA", "ITUB4.SA", "BBDC4.SA", "BBAS3.SA",
    "WEGE3.SA", "PRIO3.SA", "ABEV3.SA", "RENT3.SA", "SUZB3.SA",
    "ELET3.SA", "EQTL3.SA", "RADL3.SA", "B3SA3.SA", "GGBR4.SA",
]

US_TICKERS = [
    "AAPL", "MSFT", "NVDA", "TSLA", "META", "AMZN", "GOOGL",
]

RADAR_MODES = {
    "TENDENCIA_SAUDAVEL": "Tendência Saudável",
    "PULLBACK_DE_ALTA": "Pullback de Alta",
    "BREAKOUT_SETUP": "Breakout Setup",
    "RECUPERACAO_INICIAL": "Recuperação Inicial",
}

STATUS_THRESHOLDS = {
    (85, 100): "PRIORIDADE_ALTA",
    (75, 84): "BOM_CANDIDATO",
    (60, 74): "CANDIDATO_OBSERVAVEL",
    (40, 59): "MONITORAR_FRACO",
    (0, 39): "IGNORAR",
}
